[build]
  command = "rm -rf node_modules package-lock.json packages/web-app/node_modules packages/web-app/package-lock.json && npm install && npm --workspace=packages/web-app run build"
  publish = "packages/web-app/dist"

[[redirects]]
  from = "/webdav-proxy/*"
  to = "https://dav.jianguoyun.com/:splat"
  status = 200

[[headers]]
  for = "/geo/*"
  [headers.values]
    Cache-Control = "public, max-age=86400, s-maxage=604800, stale-while-revalidate=86400"
    Access-Control-Allow-Origin = "*"

